spring:
  application.name: rodin
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:rodin_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rodin:
  telegram:
    host: "https://api.telegram.org"
    bot-segment: 'bot'
  get-updates:
    cron: '*/5 * * * * *'
  send-messages:
    cron: '0 0 8 * * *'

server:
  port: 8080
management:
  server:
    port: 8081
